#!/usr/bin/env python

import socket
import os

BUFFER_SIZE = 1024 # Normally 1024, but we want fast response

logfile="/var/log/ipregd.log"

#check if logfile existing, if yes, delete it
if ( os.path.isfile(logfile) ):
    #delete existing log file
    os.remove(logfile)

try:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(('', 8890))
    s.listen(5)

    while 1:
        conn, addr = s.accept()
        data = conn.recv(BUFFER_SIZE)
        if not data: break
        print "Connection Address:", addr, "INFO:", data
        conn.send("IP registed")
        conn.close()

        #write log file
        f = open(logfile, 'a+')
        f.write("Connection Address: "+data+"\n")
        f.close()
except:
     print "socket failure!"
     s.close()
     exit(0)
