#!/usr/bin/env python

import socket
import fcntl
import struct
import etcd

def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

#ipaddr = ' enp0s25 ' + get_ip_address('enp0s25')

ipaddr=ipaddr=socket.gethostbyname_ex(socket.gethostname())

client = etcd.Client('10.181.40.142', port=4001)

key='service_dis/' + socket.gethostname()

client.write(key,ipaddr,ttl=60)

