#!/bin/bash

docker stop nginx-www
docker rm nginx-www

docker run --name="nginx-www" --hostname="nginx-www" \
      -d --restart=always \
      -v /media/nginx:/etc/nginx \
      -v /media/nginx/log:/var/log/nginx/log \
      -v /media/data:/download \
      --link photoshow:photoshow \
      -p 80:80 nginx:latest
