#!/usr/bin/env python

def display_ip(child):
   i=0
   for msg in child.value.split():
       if (i == 0):
          print msg
          i=1
       else:
          print "\t"+msg


import etcd

client = etcd.Client('10.181.40.142', port=4001)

for child in client.read('service_dis').children:
        display_ip(child)

