#!/usr/bin/python

import os

for root, dirs, files in os.walk("/media/data/Family-Photo", topdown=False):
    for name in files:
        if name == ".picasa.ini":
            print(os.path.join(root,name))
            os.remove(os.path.join(root,name))
